[package]
name = "mango"
version = "0.1.0"
edition = "2024"

[dependencies]
finnhub = "0.2.1"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
chrono = { version = "0.4.38" }
rfc3339 = "0.1.0"
owo-colors = "4.2.3"
